# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = sp-exam-project

QT = core gui widgets

HEADERS = \
   $$PWD/cmake-build-debug/_deps/doctest-src/doctest/extensions/doctest_mpi.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/doctest/extensions/doctest_util.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/doctest/extensions/mpi_reporter.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/doctest/extensions/mpi_sub_comm.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/doctest/parts/doctest_fwd.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/doctest/doctest.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/doctest_proxy.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/header.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/foo.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/installed_doctest_cmake/dll/dll.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/installed_doctest_cmake/dll/exporting.h \
   $$PWD/cmake-build-debug/_deps/doctest-src/scripts/development_only/doctest/doctest.h \
   $$PWD/cmake-build-debug/bin/src/sp_exam_project_autogen/moc_predefs.h \
   $$PWD/cmake-build-debug/lib/src/stochastic-simulation_autogen/moc_predefs.h \
   $$PWD/cmake-build-release/_deps/doctest-src/doctest/extensions/doctest_mpi.h \
   $$PWD/cmake-build-release/_deps/doctest-src/doctest/extensions/doctest_util.h \
   $$PWD/cmake-build-release/_deps/doctest-src/doctest/extensions/mpi_reporter.h \
   $$PWD/cmake-build-release/_deps/doctest-src/doctest/extensions/mpi_sub_comm.h \
   $$PWD/cmake-build-release/_deps/doctest-src/doctest/parts/doctest_fwd.h \
   $$PWD/cmake-build-release/_deps/doctest-src/doctest/doctest.h \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/doctest_proxy.h \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/header.h \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/foo.h \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/installed_doctest_cmake/dll/dll.h \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/installed_doctest_cmake/dll/exporting.h \
   $$PWD/cmake-build-release/_deps/doctest-src/scripts/development_only/doctest/doctest.h \
   $$PWD/lib/examples/circadian_rythm.hpp \
   $$PWD/lib/examples/covid-19.hpp \
   $$PWD/lib/examples/exponential_decay.hpp \
   $$PWD/lib/examples/mutli_threading.hpp \
   $$PWD/lib/include/agent.hpp \
   $$PWD/lib/include/charter.hpp \
   $$PWD/lib/include/generator.h \
   $$PWD/lib/include/multithreading.hpp \
   $$PWD/lib/include/observer.hpp \
   $$PWD/lib/include/random.hpp \
   $$PWD/lib/include/reaction.hpp \
   $$PWD/lib/include/simulator.hpp \
   $$PWD/lib/include/species.hpp \
   $$PWD/lib/include/state.hpp \
   $$PWD/lib/include/symbol_table.hpp \
   $$PWD/lib/include/trajectory_chart_widget.hpp \
   $$PWD/lib/include/trajectory_logger.hpp \
   $$PWD/lib/include/vessels.hpp

SOURCES = \
   $$PWD/bin/src/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/bin/src/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/bin/src/cmake-build-release/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/bin/src/cmake-build-release/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/bin/src/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/doctest/parts/doctest.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/alternative_macros.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/assert_returns_disabled.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/assert_returns_disabled_evaluate.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/assertion_macros.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/asserts_used_outside_of_tests.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/concurrency.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/coverage_maxout.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/decomposition.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/double_stringification.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/enums.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/logging.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace1.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace2.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace3.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace4.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace5.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace6.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace7.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace8.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/namespace9.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/no_failures.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/reporters_and_listeners.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/stringification.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/subcases.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/templated_test_cases.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features/test_cases_and_suites.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/default.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/return42.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/test_runner.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/exe_with_static_libs/lib_1_src1.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/exe_with_static_libs/lib_1_src2.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/exe_with_static_libs/lib_2_src.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/exe_with_static_libs/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/executable_dll_and_plugin/dll.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/executable_dll_and_plugin/implementation.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/executable_dll_and_plugin/implementation_2.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/executable_dll_and_plugin/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/executable_dll_and_plugin/plugin.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/installed_doctest_cmake/dll/dll.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/installed_doctest_cmake/dll/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/installed_doctest_cmake/executable/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/mpi/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/examples/mpi/mpi.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/scripts/how_stuff_works/how_exception_translators_work.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/scripts/how_stuff_works/how_subcases_work.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/scripts/how_stuff_works/testing_crash_scenarios.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/scripts/playground/main.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/scripts/playground/test.cpp \
   $$PWD/cmake-build-debug/_deps/doctest-src/scripts/hello_world.cpp \
   $$PWD/cmake-build-debug/bin/src/sp_exam_project_autogen/mocs_compilation.cpp \
   $$PWD/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/cmake-build-debug/lib/src/stochastic-simulation_autogen/73M2WF7Z5W/moc_trajectory_chart_widget.cpp \
   $$PWD/cmake-build-debug/lib/src/stochastic-simulation_autogen/mocs_compilation.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/doctest/parts/doctest.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/alternative_macros.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/assert_returns_disabled.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/assert_returns_disabled_evaluate.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/assertion_macros.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/asserts_used_outside_of_tests.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/concurrency.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/coverage_maxout.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/decomposition.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/double_stringification.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/enums.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/logging.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace1.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace2.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace3.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace4.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace5.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace6.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace7.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace8.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/namespace9.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/no_failures.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/reporters_and_listeners.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/stringification.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/subcases.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/templated_test_cases.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features/test_cases_and_suites.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/default.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/return42.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects/test_runner.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/exe_with_static_libs/lib_1_src1.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/exe_with_static_libs/lib_1_src2.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/exe_with_static_libs/lib_2_src.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/exe_with_static_libs/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/executable_dll_and_plugin/dll.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/executable_dll_and_plugin/implementation.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/executable_dll_and_plugin/implementation_2.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/executable_dll_and_plugin/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/executable_dll_and_plugin/plugin.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/installed_doctest_cmake/dll/dll.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/installed_doctest_cmake/dll/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/installed_doctest_cmake/executable/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/mpi/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/examples/mpi/mpi.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/scripts/how_stuff_works/how_exception_translators_work.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/scripts/how_stuff_works/how_subcases_work.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/scripts/how_stuff_works/testing_crash_scenarios.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/scripts/playground/main.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/scripts/playground/test.cpp \
   $$PWD/cmake-build-release/_deps/doctest-src/scripts/hello_world.cpp \
   $$PWD/cmake-build-release/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/cmake-build-release/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/lib/examples/circadian_rythm.cpp \
   $$PWD/lib/examples/covid-19.cpp \
   $$PWD/lib/examples/exponential_decay.cpp \
   $$PWD/lib/examples/mutli_threading.cpp \
   $$PWD/lib/src/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/lib/src/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/lib/src/cmake-build-release/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/lib/src/cmake-build-release/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/lib/src/agent.cpp \
   $$PWD/lib/src/charter.cpp \
   $$PWD/lib/src/multithreading.cpp \
   $$PWD/lib/src/observer.cpp \
   $$PWD/lib/src/random.cpp \
   $$PWD/lib/src/reaction.cpp \
   $$PWD/lib/src/simulator.cpp \
   $$PWD/lib/src/state.cpp \
   $$PWD/lib/src/symbol_table.cpp \
   $$PWD/lib/src/trajectory_chart_widget.cpp \
   $$PWD/test/SymbolTableTests.cpp

INCLUDEPATH = \
    $$PWD/cmake-build-debug/_deps/doctest-src/doctest \
    $$PWD/cmake-build-debug/_deps/doctest-src/doctest/extensions \
    $$PWD/cmake-build-debug/_deps/doctest-src/doctest/parts \
    $$PWD/cmake-build-debug/_deps/doctest-src/examples/all_features \
    $$PWD/cmake-build-debug/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects \
    $$PWD/cmake-build-debug/_deps/doctest-src/examples/installed_doctest_cmake/dll \
    $$PWD/cmake-build-debug/_deps/doctest-src/scripts/development_only/doctest \
    $$PWD/cmake-build-debug/bin/src/sp_exam_project_autogen \
    $$PWD/cmake-build-debug/lib/src/stochastic-simulation_autogen \
    $$PWD/cmake-build-release/_deps/doctest-src/doctest \
    $$PWD/cmake-build-release/_deps/doctest-src/doctest/extensions \
    $$PWD/cmake-build-release/_deps/doctest-src/doctest/parts \
    $$PWD/cmake-build-release/_deps/doctest-src/examples/all_features \
    $$PWD/cmake-build-release/_deps/doctest-src/examples/combining_the_same_tests_built_differently_in_multiple_shared_objects \
    $$PWD/cmake-build-release/_deps/doctest-src/examples/installed_doctest_cmake/dll \
    $$PWD/cmake-build-release/_deps/doctest-src/scripts/development_only/doctest \
    $$PWD/lib/include

#DEFINES = 

